# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Jezzali
tagline:          The Sewerbird Blog
url:              http://sewerbird.github.io
paginate:         1
baseurl:          /
author:
  name:           Edward Miller
  url:            https://twitter.com/ekmiv
  email:          sewerbird@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/sewerbird/sewerbird.github.io
