#!/bin/bash

TIME=$(date +"%Y-%m-%dT%H:%M:%S")
DATE=$(date +"%Y-%m-%d")
BLOG="blog/_posts/$DATE-$1.md"
TZ=$(date +"%z")

sublime "$BLOG"

echo "---
layout: post
date: '$TIME${TZ:0:3}:00'
title: $1
tagline: $2
featured: 0
---" >> "$BLOG"
