---
layout: post
title: A Summary of Adventures Unwritten!
date: '2012-01-24T12:26:00.000-08:00'
author: Edward Miller
tags: 
modified_time: '2012-01-24T12:26:48.334-08:00'
blogger_id: tag:blogger.com,1999:blog-650763852144575282.post-3214327152333403501
blogger_orig_url: http://prcadventure.blogspot.com/2012/01/summary-of-adventures-unwritten.html
---

Hey there! I have kept on playing, but with an emphasis on coming up with a bit of a plot for Our Heroes to follow, and it doesn't seem to do justice to that for me to do combat summaries. However, lately I've been a bit too busy to play the games *AND* do full nice write-ups, so will not likely be able to post what I'd like to, quality wise. So, I'll write summaries at each level for now. <br /><br />Level 9: Thieves in the Night<br />Our heroes are relaxing at Mia's alchemical apothecary when a whole den of thieves storms in upstairs and through the front door. Two thief brutes with a vicious mastiff attack our heroes while they are sipping on tea, while 5 thieves upstairs root through Mia's stock looking for something! Our heroes are pinned against the wall and send the brutes and their dogs packing and rush upstairs as quick as possible. Three thieves jump out the window with a stolen vial of Deathbloom Serum Mia had hidden, and two thief warriors fight a delaying action. After killing the warriors, Our Heroes dash into the night, towards the docks, in pursuit of the burglars. Losing track of them for a moment, they stumble upon them and see them duck into a hideout by a pier: a storehouse for seal clubbers.<br /><br />Mia and Saribke knock down the front door and toss firebombs at the thieves, fighting off a thief mage and two chainfighters, and end up having to fight an Oni in the basement who has the deathly serum. After a difficult fight with the Oni, the Oni manages to escape. However, after searching the place and deciphering a coded diary, the heroes are able to uncover a plot to murder the local Prefect at a dinner party the next day. Our heroes go to sleep at a local inn, but they are ambushed at night by two doppleganger assassins. Fighting unarmored, it is a close fight but they manage to kill the shapeshifters before coming to a fatal end. They try to sleep until morning, where they will have to figure a way to warn the prefect.